new_local_repository(
    name = "com_github_twitchtv_twirp",
    path = "/Users/john/code/go/src/github.com/twitchtv/twirp/protoc-gen-twirp",
    build_file = "BUILD.twirp.bzl",
)

http_archive(
    name = "io_bazel_rules_go",
    urls = ["https://github.com/bazelbuild/rules_go/releases/download/0.13.0/rules_go-0.13.0.tar.gz"],
    sha256 = "ba79c532ac400cefd1859cbc8a9829346aa69e3b99482cd5a54432092cbc3933",
)

load("@io_bazel_rules_go//go:def.bzl", "go_rules_dependencies", "go_register_toolchains")
go_rules_dependencies()
go_register_toolchains()


